### ISSUE TITLE
Join Team button is not working

### ISSUE THREAD

**Issue by TheOneAboveAllTitan** [releax/releax.github.io#4]
Join team button on [website](https://releax.github.io/team.html) is not working 
 Looks like there is no link provided in anchor tag.
![image](https://user-images.githubusercontent.com/32094433/64060046-0c8c9580-cbe5-11e9-901c-53f074287f0a.png)

**Comment by itsManjeet** [comment]
new link added for join team, after clicking on Team tab , 
![Screenshot_2019-10-18_20-22-09](https://user-images.githubusercontent.com/33650320/67104684-04180a80-f1e5-11e9-8171-82e465b6a73a.png)
